spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
  profiles:
     active: native
  application:
    name: config

server:
  port: 8888

security:
  user:
    name: user
    password: password