hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

  routes:
    code:
        path: /code/**
        url: http://localhost:10004
        stripPrefix: false
        sensitiveHeaders:
    dataset:
        path: /dataset/**
        url: http://localhost:10003
        stripPrefix: false
        sensitiveHeaders:
    poc:
        path: /**
        url: http://localhost:8081
        stripPrefix: false
        sensitiveHeaders:

server:
  port: 4000

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10     # 心跳间隔（秒），默认30s
    leaseExpirationDurationInSeconds: 30  # 失效时间，默认90s，如果服务在指定的 失效时间 内仍没有发起心跳请求，将会被剔除EurekaServer
    prefer-ip-address: true               # 实例名称显示IP配置（与instance-id配合使用）
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}  # 将InstanceID设置为 IP:Port 形式
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
    healthcheck:
      enable: true
